### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by qiyi71w** [DaneWang9513/BFV_RADAR-AIMBOT#2]
运行窗口大小: 1920 x 1080
[+] Searching for BFV.exe
Traceback (most recent call last):
  File "assist.py", line 72, in <module>
    aimer.start()
  File "F:\BFV_RADAR-AIMBOT-master\lib\aimer.py", line 52, in start
    phandle = BFV.get_handle()
  File "F:\BFV_RADAR-AIMBOT-master\lib\BFV.py", line 55, in get_handle
    pid = api.get_processid_by_name("bfv.exe")
  File "F:\BFV_RADAR-AIMBOT-master\lib\MemAccess.py", line 164, in get_processid_by_name
    if procname.decode("utf-8").lower() == name.lower():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 2: invalid continuation byte

**Comment by qiyi71w** [comment]
MemAccess.py里面
if procname.decode("UTF-8").lower() == name.lower():  改为if procname.decode("gbk").lower() == name.lower():
